name: Publish Docker image

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/offmap

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # 1. 'latest' tag for main branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=sha

            # 2. Semver tags for v1.x.x and v1
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            
            # 3. 'develop' tag explicitly for pull requests
            type=raw,value=develop,enable=${{ github.event_name == 'pull_request' }}
            
            # 4. PR specific tags (e.g., pr-2)
            type=ref,event=pr
            
            # 5. Branch name tags for branches other than main (e.g., feature/update-proxy)
            type=ref,event=branch

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
